server:
  port: 8081

spring:
  application:
    name: datafusion-agent

datafusion:
  agent:
    modules: ${DATAFUSION_MODULES:${user.dir}}
    worker:
      worker-code: ${DATAFUSION_WORKER_CODE:}
      port: ${server.port:8081}
      accept-tasks-before-registered: false
    manager:
      base-url: ${DATAFUSION_MANAGER_URL:http://datafusion-manager}
      enabled: true
      heartbeat-interval-ms: 15000
    storage:
      logs-dir: logs
      task-runtime-dir: ${DATAFUSION_TASK_RUNTIME_DIR:/opt/datafusion/task-runtime}
    task-pool:
      core-pool-size: 8
      max-pool-size: 16
      queue-capacity: 512
      keep-alive-seconds: 60
    report-pool:
      core-pool-size: 2
      max-pool-size: 4
      queue-capacity: 512
      keep-alive-seconds: 60
